#!/bin/bash

# ... other code ...

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

# ... other code ...

if [[ "${BASH_SOURCE[0]:-$0}" == "${0}" ]]; then
    # ... other code ...
}

# ... other code ...
